packages/theme/src/index.ts
packages/theme/src/light-dom/modals.scss
packages/theme/src/light-dom/vaadin.scss
packages/theme/src/shadowDom/cssAll.ts
packages/theme/src/shadowDom/cssAnimations.ts
packages/theme/src/shadowDom/cssTooltip.ts
packages/web/src/animations/installing.ts
packages/web/src/index.ts
packages/web/src/mixins/entityStorePath.ts
packages/web/src/tooltip.ts

Related to https://github.com/c6o/node-monorepo/issues/116

feat(css): App install animation and dialog styles

---

packages/web/src/formInputs/combobox.ts
packages/web/src/formInputs/select.ts
packages/web/src/registerStyles.ts

Related to https://github.com/c6o/node-monorepo/issues/826

fix(hub): Ability to select marketplace category when editing an app

---

packages/web/src/dialog/dialogStore.ts

Related to https://github.com/c6o/node-monorepo/issues/867

chore: add render() to interface

---

packages/web/src/formInputs/textArea.ts
packages/web/src/markdown.ts
packages/web/src/registerStyles.ts

Related to https://github.com/c6o/node-monorepo/issues/875

chore: Show markdown toolbar again and remove @font-face. Font will come from CDN.

---

packages/theme/src/light-dom/modals.scss

Related to https://github.com/c6o/node-monorepo/issues/870

chore: Tweak to our modal css

---

packages/web/src/router.ts

WARNING! Don't sync develop to this commit manually. Wait for a PR on node-monorepo to do it.

chore: Simplify the router util methods; remove 'redirect' and just use 'navigate'

---

packages/web/src/router.ts

My "navigate" refactor also broke the marketplace search field for when the entered value is cleared.

fix: Fix for clearing the marketplace search field

---

packages/theme/src/shadowDom/cssBase.ts

fix: Fix css variable typo

---

packages/web/src/formInputs/textArea.ts

Fixes https://github.com/c6o/node-monorepo/issues/890

fix: Check for empty object or string instead of just empty string

---

packages/web/src/dialog/simpleDialog.ts
packages/web/src/formInputs/textField.ts

Part of the work for https://github.com/c6o/node-monorepo/issues/919

feat: Welcome dialog and text field enhancements

---

packages/theme/src/light-dom/base.scss
packages/web/src/button.ts
packages/web/src/registerStyles.ts

Related to https://github.com/c6o/node-monorepo/issues/932

feat: You can now pass a store to the c6o-button component and show saving success or error next to the button

---

packages/web/src/form/results.ts
packages/web/src/formInputs/textArea.ts
packages/web/src/store/state.ts

Fixes https://github.com/c6o/node-monorepo/issues/965

fix: State Manager component, and TextArea component rendering issues

---

packages/web/src/dialog/dialogStore.ts
packages/web/src/formInputs/combobox.ts
packages/web/src/formInputs/select.ts
packages/web/src/formInputs/textField.ts
packages/web/src/layout/contextualSubnav.ts

chore: Edit to the CSS to align text better

---

packages/web/src/animations/loading.ts
packages/web/src/store/panel.ts
packages/web/src/store/state.ts

We had some extra logic in these components that wasn't being used anywhere, so it's been removed.

chore: Simplify the c6o-state and c6o-loading components

---

packages/web/package.json
packages/web/src/dialog/dialog.ts
packages/web/src/index.ts
packages/web/src/styles.ts
yarn.lock

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

Added web-dialog

---

packages/theme/src/light-dom/css-variables.scss
packages/web/src/tabs/horizontalTabs.ts
packages/web/src/tabs/index.ts
packages/web/src/tabs/navigationTabs.ts
packages/web/src/tabs/verticalTabs.ts

chore: Horizontal and Vertical tab components

---

packages/web/src/formInputs/checkbox/checkboxGroup.ts
packages/web/src/formInputs/checkbox/index.ts
packages/web/src/formInputs/checkbox/styles.ts

Fixes #1284
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

feat: CheckboxGroup component with an example for a required acceptance checkbox

---

packages/web/src/mixins/entityListStore.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Optional:

fix: EntityListStoreMixin properly observes entityStore changes

---

packages/web/src/formInputs/select/select.ts
packages/web/src/layouts/verticalMenu.ts
packages/web/src/mixins/entityListStore.ts

Fix some non-breaking console errors.

fix: Resolve a couple of console errors in components

---

packages/web/src/buttons/saveButton.ts
packages/web/src/dialogs/baseStoreDialog.ts
packages/web/src/form/results.ts
packages/web/src/formInputs/select/select.ts
packages/web/src/formInputs/textFields/textField.ts

Related to: https://github.com/c6o/node-monorepo/pull/1426

chore: Use the hasSuccess computed from the base/entity store refactor
